name: Refresh

on:
  workflow_dispatch:
  schedule:
    - cron: '*/60 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          wget 'https://raw.githubusercontent.com/saschazesiger/Free-Proxies/master/proxies/ultrafast.txt'
          pip install requests black wheel fake-headers
      - name: Run
        run: |
          python control.py
      - name: Commit
        run: |
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git config --local user.name 'github-actions[bot]'
          git remote set-url origin 'https://x-access-token:${{ secrets.GB_TOKEN }}@github.com/yuceltoluyag/GoodProxy.git'
          git add  .
          git commit -am "Updated Proxies"
          git push